# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            DCPixel
tagline:          'From Content to Value'
description:      'We develop web applications designed to meet your specific business needs'
url:              https://dcpixel.gr
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://github.com/dcpixel/dcpixel

paginate:         5

# Custom vars

