# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            DCPixel
tagline:          'Custom Website Development'
description:      'We develop secure websites based on Internet technologies designed to meet your specific business needs'
url:              https://dcpixel.gr
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://github.com/dcpixel/dcpixel

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

